# 当前 storage 所属的 group
# 同一个 group 内的 storage 后期会互相同步文件
group_name = group1

# storage 监听端口
# 客户端上传/下载文件时会连接这个端口
port = 23000

# storage 的基础目录
# 后面用于保存日志、binlog、状态文件等
base_path = ./data/storage1

# 真正保存文件的路径
# 后期可以扩展 store_path1、store_path2 来表示多块磁盘
store_path0 = ./data/storage1/files

# tracker 地址
# storage 启动后会连接 tracker 并注册自己
tracker_server = 127.0.0.1:22122

# 心跳间隔，单位：秒
# storage 会定期告诉 tracker：我还活着
heart_beat_interval = 5

# 磁盘状态上报间隔，单位：秒
# 后面用于向 tracker 上报剩余空间、总容量等信息
stat_report_interval = 30