# tracker 监听端口
# 后面客户端和 storage 都会连接这个端口
port = 22122

# tracker 的基础目录
# 后面用于保存日志、storage 状态、元信息等
base_path = ./data/tracker

# 存储节点选择策略
# round_robin 表示轮询
# 后面还会支持 max_free_space、specify_group 等策略
store_lookup = round_robin

# tracker 检查 storage 是否存活的时间间隔，单位：秒
check_active_interval = 10